// Region definitions: (svg_id, name_msgid).
// At runtime we call gettext(name_msgid) to get the translated display name.
// N_ is a no-op that marks strings for xgettext extraction (--keyword=N_).

#[allow(non_snake_case)]
pub const fn N_(s: &str) -> &str {
    s
}

// NC_ marks a string that carries a gettext message context for extraction
// (--keyword=NC_:1c,2). It returns the msgid; the context is applied at
// runtime via pgettext(context, msgid).
#[allow(non_snake_case)]
pub const fn NC_(_context: &str, msgid: &'static str) -> &'static str {
    msgid
}

pub const ITALY_REGIONS: &[(&str, &str)] = &[
    ("Abruzzo", N_("Abruzzo")),
    ("Basilicata", N_("Basilicata")),
    ("Calabria", N_("Calabria")),
    ("Campania", N_("Campania")),
    ("Emilia-Romagna", N_("Emilia-Romagna")),
    ("Friuli Venezia Giulia", N_("Friuli Venezia Giulia")),
    ("Lazio", N_("Lazio")),
    ("Liguria", N_("Liguria")),
    ("Lombardy", N_("Lombardy")),
    ("Marche", N_("Marche")),
    ("Molise", N_("Molise")),
    ("Piedmont", N_("Piedmont")),
    ("Puglia", N_("Apulia")),
    ("Sardegna", N_("Sardinia")),
    ("Sicilia", N_("Sicily")),
    ("Trentino-Alto Adige", N_("Trentino-South Tyrol")),
    ("Tuscany", N_("Tuscany")),
    ("Umbria", N_("Umbria")),
    ("Valle d'Aosta", N_("Aosta Valley")),
    ("Veneto", N_("Veneto")),
];

pub const GERMANY_STATES: &[(&str, &str)] = &[
    ("Baden-Württemberg", N_("Baden-Württemberg")),
    ("Bavaria", N_("Bavaria")),
    ("Berlin", N_("Berlin")),
    ("Brandenburg", N_("Brandenburg")),
    ("Bremen", N_("Bremen")),
    ("Hamburg", N_("Hamburg")),
    ("Hesse", N_("Hesse")),
    ("Lower Saxony", N_("Lower Saxony")),
    (
        "Mecklenburg-Western Pomerania",
        N_("Mecklenburg-Western Pomerania"),
    ),
    ("North Rhine-Westphalia", N_("North Rhine-Westphalia")),
    ("Rhineland-Palatinate", N_("Rhineland-Palatinate")),
    ("Saarland", N_("Saarland")),
    ("Saxony", N_("Saxony")),
    ("Saxony-Anhalt", N_("Saxony-Anhalt")),
    ("Schleswig-Holstein", N_("Schleswig-Holstein")),
    ("Thuringia", N_("Thuringia")),
];

pub const GERMANY_STATE_CAPITALS: &[(&str, &str)] = &[
    (N_("Berlin"), N_("Berlin")),
    (N_("Bremen"), N_("Bremen")),
    (N_("Dresden"), N_("Saxony")),
    (N_("Düsseldorf"), N_("North Rhine-Westphalia")),
    (N_("Erfurt"), N_("Thuringia")),
    (N_("Hamburg"), N_("Hamburg")),
    (N_("Hanover"), N_("Lower Saxony")),
    (N_("Kiel"), N_("Schleswig-Holstein")),
    (N_("Magdeburg"), N_("Saxony-Anhalt")),
    (N_("Mainz"), N_("Rhineland-Palatinate")),
    (N_("Munich"), N_("Bavaria")),
    (N_("Potsdam"), N_("Brandenburg")),
    (N_("Saarbrücken"), N_("Saarland")),
    (N_("Schwerin"), N_("Mecklenburg-Western Pomerania")),
    (N_("Stuttgart"), N_("Baden-Württemberg")),
    (N_("Wiesbaden"), N_("Hesse")),
];

pub const SPAIN_COMMUNITIES: &[(&str, &str)] = &[
    ("Andalucía", N_("Andalusia")),
    ("Aragón", N_("Aragon")),
    ("Asturias", N_("Asturias")),
    ("Islas Baleares", N_("Balearic Islands")),
    ("Canarias", N_("Canary Islands")),
    ("Cantabria", N_("Cantabria")),
    ("Castilla-La Mancha", N_("Castilla-La Mancha")),
    ("Castilla y León", N_("Castile and León")),
    ("Cataluña", N_("Catalonia")),
    ("Ceuta", N_("Ceuta")),
    ("Extremadura", N_("Extremadura")),
    ("Galicia", N_("Galicia")),
    ("La Rioja", N_("La Rioja")),
    ("Madrid", N_("Madrid")),
    ("Melilla", N_("Melilla")),
    ("Murcia", N_("Murcia")),
    ("Navarra", N_("Navarre")),
    ("País Vasco", N_("Basque Country")),
    ("Valencia", N_("Valencia")),
];

pub const SPAIN_COMMUNITY_CAPITALS: &[(&str, &str)] = &[
    (N_("Barcelona"), N_("Catalonia")),
    (N_("Ceuta"), N_("Ceuta")),
    (N_("Logroño"), N_("La Rioja")),
    (N_("Madrid"), N_("Madrid")),
    (N_("Melilla"), N_("Melilla")),
    (N_("Mérida"), N_("Extremadura")),
    (N_("Murcia"), N_("Murcia")),
    (N_("Oviedo"), N_("Asturias")),
    (N_("Palma"), N_("Balearic Islands")),
    (N_("Pamplona"), N_("Navarre")),
    (N_("Santa Cruz de Tenerife"), N_("Canary Islands")),
    (N_("Santander"), N_("Cantabria")),
    (N_("Santiago de Compostela"), N_("Galicia")),
    (N_("Seville"), N_("Andalusia")),
    (N_("Toledo"), N_("Castilla-La Mancha")),
    (N_("Valencia"), N_("Valencia")),
    (N_("Valladolid"), N_("Castile and León")),
    (N_("Vitoria-Gasteiz"), N_("Basque Country")),
    (N_("Zaragoza"), N_("Aragon")),
];

pub const SPAIN_PROVINCES: &[(&str, &str)] = &[
    ("A Coruña", N_("A Coruña")),
    ("Albacete", N_("Albacete")),
    ("Alicante", N_("Alicante")),
    ("Almería", N_("Almería")),
    ("Asturias", N_("Asturias")),
    ("Badajoz", N_("Badajoz")),
    ("Barcelona", N_("Barcelona")),
    ("Burgos", N_("Burgos")),
    ("Cantabria", N_("Cantabria")),
    ("Castellón", N_("Castellón")),
    ("Ciudad Real", N_("Ciudad Real")),
    ("Cuenca", N_("Cuenca")),
    ("Cáceres", N_("Cáceres")),
    ("Cádiz", N_("Cádiz")),
    ("Córdoba", N_("Córdoba")),
    ("Girona", N_("Girona")),
    ("Granada", N_("Granada")),
    ("Guadalajara", N_("Guadalajara")),
    ("Guipúzcoa", N_("Gipuzkoa")),
    ("Huelva", N_("Huelva")),
    ("Huesca", N_("Huesca")),
    ("Islas Baleares", N_("Balearic Islands")),
    ("Jaén", N_("Jaén")),
    ("La Rioja", N_("La Rioja")),
    ("Las Palmas", N_("Las Palmas")),
    ("León", N_("León")),
    ("Lleida", N_("Lleida")),
    ("Lugo", N_("Lugo")),
    ("Madrid", N_("Madrid")),
    ("Murcia", N_("Murcia")),
    ("Málaga", N_("Málaga")),
    ("Navarra", N_("Navarre")),
    ("Ourense", N_("Ourense")),
    ("Palencia", N_("Palencia")),
    ("Pontevedra", N_("Pontevedra")),
    ("Salamanca", N_("Salamanca")),
    ("Santa Cruz de Tenerife", N_("Santa Cruz de Tenerife")),
    ("Segovia", N_("Segovia")),
    ("Sevilla", N_("Seville")),
    ("Soria", N_("Soria")),
    ("Tarragona", N_("Tarragona")),
    ("Teruel", N_("Teruel")),
    ("Toledo", N_("Toledo")),
    ("Valencia", N_("Valencia")),
    ("Valladolid", N_("Valladolid")),
    ("Vizcaya", N_("Biscay")),
    ("Zamora", N_("Zamora")),
    ("Zaragoza", N_("Zaragoza")),
    ("Álava", N_("Álava")),
    ("Ávila", N_("Ávila")),
];

pub const WORLD_CONTINENTS: &[(&str, &str)] = &[
    ("Africa", N_("Africa")),
    ("Asia", N_("Asia")),
    ("Europe", N_("Europe")),
    ("North America", N_("North America")),
    ("Oceania", N_("Oceania")),
    ("South America", N_("South America")),
];

pub const EUROPE_COUNTRIES: &[(&str, &str)] = &[
    ("Albania", N_("Albania")),
    ("Andorra", N_("Andorra")),
    ("Armenia", N_("Armenia")),
    ("Austria", N_("Austria")),
    ("Azerbaijan", N_("Azerbaijan")),
    ("Belarus", N_("Belarus")),
    ("Belgium", N_("Belgium")),
    ("Bosnia and Herzegovina", N_("Bosnia and Herzegovina")),
    ("Bulgaria", N_("Bulgaria")),
    ("Croatia", N_("Croatia")),
    ("Cyprus", N_("Cyprus")),
    ("Czech Republic", N_("Czech Republic")),
    ("Denmark", N_("Denmark")),
    ("Estonia", N_("Estonia")),
    ("Finland", N_("Finland")),
    ("France", N_("France")),
    ("Georgia", N_("Georgia")),
    ("Germany", N_("Germany")),
    ("Greece", N_("Greece")),
    ("Hungary", N_("Hungary")),
    ("Iceland", N_("Iceland")),
    ("Ireland", N_("Ireland")),
    ("Italy", N_("Italy")),
    ("Kosovo", N_("Kosovo")),
    ("Latvia", N_("Latvia")),
    ("Liechtenstein", N_("Liechtenstein")),
    ("Lithuania", N_("Lithuania")),
    ("Luxembourg", N_("Luxembourg")),
    ("Malta", N_("Malta")),
    ("Moldova", N_("Moldova")),
    ("Monaco", N_("Monaco")),
    ("Montenegro", N_("Montenegro")),
    ("Netherlands", N_("Netherlands")),
    ("North Macedonia", N_("North Macedonia")),
    ("Norway", N_("Norway")),
    ("Poland", N_("Poland")),
    ("Portugal", N_("Portugal")),
    ("Romania", N_("Romania")),
    ("Russia", N_("Russia")),
    ("San Marino", N_("San Marino")),
    ("Serbia", N_("Serbia")),
    ("Slovakia", N_("Slovakia")),
    ("Slovenia", N_("Slovenia")),
    ("Spain", N_("Spain")),
    ("Sweden", N_("Sweden")),
    ("Switzerland", N_("Switzerland")),
    ("Turkey", N_("Turkey")),
    ("Ukraine", N_("Ukraine")),
    ("United Kingdom", N_("United Kingdom")),
    ("Vatican City", N_("Vatican City")),
];

pub const AMERICA_COUNTRIES: &[(&str, &str)] = &[
    ("Argentina", N_("Argentina")),
    ("Bahamas", N_("Bahamas")),
    ("Belize", N_("Belize")),
    ("Bolivia", N_("Bolivia")),
    ("Brazil", N_("Brazil")),
    ("Canada", N_("Canada")),
    ("Chile", N_("Chile")),
    ("Colombia", N_("Colombia")),
    ("Costa Rica", N_("Costa Rica")),
    ("Cuba", N_("Cuba")),
    ("Dominican Republic", N_("Dominican Republic")),
    ("Ecuador", N_("Ecuador")),
    ("El Salvador", N_("El Salvador")),
    ("Guatemala", N_("Guatemala")),
    ("Guyana", N_("Guyana")),
    ("Haiti", N_("Haiti")),
    ("Honduras", N_("Honduras")),
    ("Jamaica", N_("Jamaica")),
    ("Mexico", N_("Mexico")),
    ("Nicaragua", N_("Nicaragua")),
    ("Panama", N_("Panama")),
    ("Paraguay", N_("Paraguay")),
    ("Peru", N_("Peru")),
    ("Suriname", N_("Suriname")),
    ("Trinidad and Tobago", N_("Trinidad and Tobago")),
    ("United States", N_("United States")),
    ("Uruguay", N_("Uruguay")),
    ("Venezuela", N_("Venezuela")),
];

pub const AFRICA_COUNTRIES: &[(&str, &str)] = &[
    ("Algeria", N_("Algeria")),
    ("Angola", N_("Angola")),
    ("Benin", N_("Benin")),
    ("Botswana", N_("Botswana")),
    ("Burkina Faso", N_("Burkina Faso")),
    ("Burundi", N_("Burundi")),
    ("Cameroon", N_("Cameroon")),
    ("Cape Verde", N_("Cape Verde")),
    ("Central African Republic", N_("Central African Republic")),
    ("Chad", N_("Chad")),
    ("Comoros", N_("Comoros")),
    ("Côte d'Ivoire", N_("Côte d'Ivoire")),
    (
        "Democratic Republic of the Congo",
        N_("Democratic Republic of the Congo"),
    ),
    ("Djibouti", N_("Djibouti")),
    ("Egypt", N_("Egypt")),
    ("Equatorial Guinea", N_("Equatorial Guinea")),
    ("Eritrea", N_("Eritrea")),
    ("Eswatini", N_("Eswatini")),
    ("Ethiopia", N_("Ethiopia")),
    ("Gabon", N_("Gabon")),
    ("Gambia", N_("Gambia")),
    ("Ghana", N_("Ghana")),
    ("Guinea", N_("Guinea")),
    ("Guinea-Bissau", N_("Guinea-Bissau")),
    ("Kenya", N_("Kenya")),
    ("Lesotho", N_("Lesotho")),
    ("Liberia", N_("Liberia")),
    ("Libya", N_("Libya")),
    ("Madagascar", N_("Madagascar")),
    ("Malawi", N_("Malawi")),
    ("Mali", N_("Mali")),
    ("Mauritania", N_("Mauritania")),
    ("Mauritius", N_("Mauritius")),
    ("Morocco", N_("Morocco")),
    ("Mozambique", N_("Mozambique")),
    ("Namibia", N_("Namibia")),
    ("Niger", N_("Niger")),
    ("Nigeria", N_("Nigeria")),
    ("Republic of the Congo", N_("Republic of the Congo")),
    ("Rwanda", N_("Rwanda")),
    ("São Tomé and Príncipe", N_("São Tomé and Príncipe")),
    ("Senegal", N_("Senegal")),
    ("Sierra Leone", N_("Sierra Leone")),
    ("Somalia", N_("Somalia")),
    ("South Africa", N_("South Africa")),
    ("South Sudan", N_("South Sudan")),
    ("Sudan", N_("Sudan")),
    ("Tanzania", N_("Tanzania")),
    ("Togo", N_("Togo")),
    ("Tunisia", N_("Tunisia")),
    ("Uganda", N_("Uganda")),
    ("Western Sahara", N_("Western Sahara")),
    ("Zambia", N_("Zambia")),
    ("Zimbabwe", N_("Zimbabwe")),
];

pub const OCEANIA_COUNTRIES: &[(&str, &str)] = &[
    ("Australia", N_("Australia")),
    ("Fiji", N_("Fiji")),
    ("Kiribati", N_("Kiribati")),
    ("Marshall Islands", N_("Marshall Islands")),
    ("Micronesia", N_("Micronesia")),
    ("Nauru", N_("Nauru")),
    ("New Zealand", N_("New Zealand")),
    ("Palau", N_("Palau")),
    ("Papua New Guinea", N_("Papua New Guinea")),
    ("Samoa", N_("Samoa")),
    ("Solomon Islands", N_("Solomon Islands")),
    ("Tonga", N_("Tonga")),
    ("Tuvalu", N_("Tuvalu")),
    ("Vanuatu", N_("Vanuatu")),
];

pub const ASIA_COUNTRIES: &[(&str, &str)] = &[
    ("Afghanistan", N_("Afghanistan")),
    ("Armenia", N_("Armenia")),
    ("Azerbaijan", N_("Azerbaijan")),
    ("Bahrain", N_("Bahrain")),
    ("Bangladesh", N_("Bangladesh")),
    ("Bhutan", N_("Bhutan")),
    ("Brunei", N_("Brunei")),
    ("Cambodia", N_("Cambodia")),
    ("China", N_("China")),
    ("Cyprus", N_("Cyprus")),
    ("East Timor", N_("East Timor")),
    ("Georgia", N_("Georgia")),
    ("India", N_("India")),
    ("Indonesia", N_("Indonesia")),
    ("Iran", N_("Iran")),
    ("Iraq", N_("Iraq")),
    ("Israel", N_("Israel")),
    ("Japan", N_("Japan")),
    ("Jordan", N_("Jordan")),
    ("Kazakhstan", N_("Kazakhstan")),
    ("Kuwait", N_("Kuwait")),
    ("Kyrgyzstan", N_("Kyrgyzstan")),
    ("Laos", N_("Laos")),
    ("Lebanon", N_("Lebanon")),
    ("Malaysia", N_("Malaysia")),
    ("Maldives", N_("Maldives")),
    ("Mongolia", N_("Mongolia")),
    ("Myanmar", N_("Myanmar")),
    ("Nepal", N_("Nepal")),
    ("North Korea", N_("North Korea")),
    ("Oman", N_("Oman")),
    ("Pakistan", N_("Pakistan")),
    ("Palestine", N_("Palestine")),
    ("Philippines", N_("Philippines")),
    ("Qatar", N_("Qatar")),
    ("Russia", N_("Russia")),
    ("Saudi Arabia", N_("Saudi Arabia")),
    ("Singapore", N_("Singapore")),
    ("South Korea", N_("South Korea")),
    ("Sri Lanka", N_("Sri Lanka")),
    ("Syria", N_("Syria")),
    ("Taiwan", N_("Taiwan")),
    ("Tajikistan", N_("Tajikistan")),
    ("Thailand", N_("Thailand")),
    ("Turkey", N_("Turkey")),
    ("Turkmenistan", N_("Turkmenistan")),
    ("United Arab Emirates", N_("United Arab Emirates")),
    ("Uzbekistan", N_("Uzbekistan")),
    ("Vietnam", N_("Vietnam")),
    ("Yemen", N_("Yemen")),
];

pub const INDIA_STATES: &[(&str, &str)] = &[
    (
        "Andaman and Nicobar Islands",
        N_("Andaman and Nicobar Islands"),
    ),
    ("Andhra Pradesh", N_("Andhra Pradesh")),
    ("Arunachal Pradesh", N_("Arunachal Pradesh")),
    ("Assam", N_("Assam")),
    ("Bihar", N_("Bihar")),
    ("Chandigarh", N_("Chandigarh")),
    ("Chhattisgarh", N_("Chhattisgarh")),
    (
        "Dadra and Nagar Haveli and Daman and Diu",
        N_("Dadra and Nagar Haveli and Daman and Diu"),
    ),
    ("Delhi", N_("Delhi")),
    ("Goa", N_("Goa")),
    ("Gujarat", N_("Gujarat")),
    ("Haryana", N_("Haryana")),
    ("Himachal Pradesh", N_("Himachal Pradesh")),
    ("Jammu and Kashmir", N_("Jammu and Kashmir")),
    ("Jharkhand", N_("Jharkhand")),
    ("Karnataka", N_("Karnataka")),
    ("Kerala", N_("Kerala")),
    ("Ladakh", N_("Ladakh")),
    ("Lakshadweep", N_("Lakshadweep")),
    ("Madhya Pradesh", N_("Madhya Pradesh")),
    ("Maharashtra", N_("Maharashtra")),
    ("Manipur", N_("Manipur")),
    ("Meghalaya", N_("Meghalaya")),
    ("Mizoram", N_("Mizoram")),
    ("Nagaland", N_("Nagaland")),
    ("Odisha", N_("Odisha")),
    ("Puducherry", N_("Puducherry")),
    ("Punjab", N_("Punjab")),
    ("Rajasthan", N_("Rajasthan")),
    ("Sikkim", N_("Sikkim")),
    ("Tamil Nadu", N_("Tamil Nadu")),
    ("Telangana", N_("Telangana")),
    ("Tripura", N_("Tripura")),
    ("Uttar Pradesh", N_("Uttar Pradesh")),
    ("Uttarakhand", N_("Uttarakhand")),
    ("West Bengal", N_("West Bengal")),
];

pub const JAPAN_PREFECTURES: &[(&str, &str)] = &[
    ("Hokkaidō", N_("Hokkaidō")),
    ("Aomori", N_("Aomori")),
    ("Iwate", N_("Iwate")),
    ("Miyagi", N_("Miyagi")),
    ("Akita", N_("Akita")),
    ("Yamagata", N_("Yamagata")),
    ("Fukushima", N_("Fukushima")),
    ("Ibaraki", N_("Ibaraki")),
    ("Tochigi", N_("Tochigi")),
    ("Gunma", N_("Gunma")),
    ("Saitama", N_("Saitama")),
    ("Chiba", N_("Chiba")),
    ("Tokyo", N_("Tokyo")),
    ("Kanagawa", N_("Kanagawa")),
    ("Niigata", N_("Niigata")),
    ("Toyama", N_("Toyama")),
    ("Ishikawa", N_("Ishikawa")),
    ("Fukui", N_("Fukui")),
    ("Yamanashi", N_("Yamanashi")),
    ("Nagano", N_("Nagano")),
    ("Gifu", N_("Gifu")),
    ("Shizuoka", N_("Shizuoka")),
    ("Aichi", N_("Aichi")),
    ("Mie", N_("Mie")),
    ("Shiga", N_("Shiga")),
    ("Kyōto", N_("Kyōto")),
    ("Ōsaka", N_("Ōsaka")),
    ("Hyōgo", N_("Hyōgo")),
    ("Nara", N_("Nara")),
    ("Wakayama", N_("Wakayama")),
    ("Tottori", N_("Tottori")),
    ("Shimane", N_("Shimane")),
    ("Okayama", N_("Okayama")),
    ("Hiroshima", N_("Hiroshima")),
    ("Yamaguchi", N_("Yamaguchi")),
    ("Tokushima", N_("Tokushima")),
    ("Kagawa", N_("Kagawa")),
    ("Ehime", N_("Ehime")),
    ("Kōchi", N_("Kōchi")),
    ("Fukuoka", N_("Fukuoka")),
    ("Saga", N_("Saga")),
    ("Nagasaki", N_("Nagasaki")),
    ("Kumamoto", N_("Kumamoto")),
    ("Ōita", N_("Ōita")),
    ("Miyazaki", N_("Miyazaki")),
    ("Kagoshima", N_("Kagoshima")),
    ("Okinawa", N_("Okinawa")),
];

pub const US_STATES: &[(&str, &str)] = &[
    ("Alabama", N_("Alabama")),
    ("Alaska", N_("Alaska")),
    ("Arizona", N_("Arizona")),
    ("Arkansas", N_("Arkansas")),
    ("California", N_("California")),
    ("Colorado", N_("Colorado")),
    ("Connecticut", N_("Connecticut")),
    ("Delaware", N_("Delaware")),
    ("District of Columbia", N_("District of Columbia")),
    ("Florida", N_("Florida")),
    ("Georgia", N_("Georgia")),
    ("Hawaii", N_("Hawaii")),
    ("Idaho", N_("Idaho")),
    ("Illinois", N_("Illinois")),
    ("Indiana", N_("Indiana")),
    ("Iowa", N_("Iowa")),
    ("Kansas", N_("Kansas")),
    ("Kentucky", N_("Kentucky")),
    ("Louisiana", N_("Louisiana")),
    ("Maine", N_("Maine")),
    ("Maryland", N_("Maryland")),
    ("Massachusetts", N_("Massachusetts")),
    ("Michigan", N_("Michigan")),
    ("Minnesota", N_("Minnesota")),
    ("Mississippi", N_("Mississippi")),
    ("Missouri", N_("Missouri")),
    ("Montana", N_("Montana")),
    ("Nebraska", N_("Nebraska")),
    ("Nevada", N_("Nevada")),
    ("New Hampshire", N_("New Hampshire")),
    ("New Jersey", N_("New Jersey")),
    ("New Mexico", N_("New Mexico")),
    ("New York", N_("New York")),
    ("North Carolina", N_("North Carolina")),
    ("North Dakota", N_("North Dakota")),
    ("Ohio", N_("Ohio")),
    ("Oklahoma", N_("Oklahoma")),
    ("Oregon", N_("Oregon")),
    ("Pennsylvania", N_("Pennsylvania")),
    ("Rhode Island", N_("Rhode Island")),
    ("South Carolina", N_("South Carolina")),
    ("South Dakota", N_("South Dakota")),
    ("Tennessee", N_("Tennessee")),
    ("Texas", N_("Texas")),
    ("Utah", N_("Utah")),
    ("Vermont", N_("Vermont")),
    ("Virginia", N_("Virginia")),
    ("Washington", N_("Washington")),
    ("West Virginia", N_("West Virginia")),
    ("Wisconsin", N_("Wisconsin")),
    ("Wyoming", N_("Wyoming")),
];

pub const POLAND_VOIVODESHIPS: &[(&str, &str)] = &[
    ("Greater Poland", N_("Greater Poland")),
    ("Kuyavia-Pomerania", N_("Kuyavia-Pomerania")),
    ("Lesser Poland", N_("Lesser Poland")),
    ("Lower Silesia", N_("Lower Silesia")),
    ("Lublin", N_("Lublin")),
    ("Lubusz", N_("Lubusz")),
    ("Masovia", N_("Masovia")),
    ("Opole", N_("Opole")),
    ("Podlachia", N_("Podlachia")),
    ("Pomerania", N_("Pomerania")),
    ("Silesia", N_("Silesia")),
    ("Subcarpathia", N_("Subcarpathia")),
    ("Świętokrzyskie", N_("Świętokrzyskie")),
    ("Warmia-Masuria", N_("Warmia-Masuria")),
    ("West Pomerania", N_("West Pomerania")),
    ("Łódź", N_("Łódź")),
];

pub const POLAND_VOIVODESHIP_CAPITALS: &[(&str, &str)] = &[
    (N_("Białystok"), N_("Podlachia")),
    (N_("Bydgoszcz"), N_("Kuyavia-Pomerania")),
    (N_("Gdańsk"), N_("Pomerania")),
    (N_("Gorzów Wielkopolski"), N_("Lubusz")),
    (N_("Katowice"), N_("Silesia")),
    (N_("Kielce"), N_("Świętokrzyskie")),
    (N_("Kraków"), N_("Lesser Poland")),
    (N_("Lublin"), N_("Lublin")),
    (N_("Łódź"), N_("Łódź")),
    (N_("Olsztyn"), N_("Warmia-Masuria")),
    (N_("Opole"), N_("Opole")),
    (N_("Poznań"), N_("Greater Poland")),
    (N_("Rzeszów"), N_("Subcarpathia")),
    (N_("Szczecin"), N_("West Pomerania")),
    (N_("Warsaw"), N_("Masovia")),
    (N_("Wrocław"), N_("Lower Silesia")),
];

pub const PORTUGAL_DISTRICTS: &[(&str, &str)] = &[
    ("Aveiro", N_("Aveiro")),
    ("Azores", N_("Azores")),
    ("Beja", N_("Beja")),
    ("Braga", N_("Braga")),
    ("Bragança", N_("Bragança")),
    ("Castelo Branco", N_("Castelo Branco")),
    ("Coimbra", N_("Coimbra")),
    ("Faro", N_("Faro")),
    ("Guarda", N_("Guarda")),
    ("Leiria", N_("Leiria")),
    ("Lisboa", N_("Lisboa")),
    ("Madeira", N_("Madeira")),
    ("Portalegre", N_("Portalegre")),
    ("Porto", N_("Porto")),
    ("Santarém", N_("Santarém")),
    ("Setúbal", N_("Setúbal")),
    ("Viana do Castelo", N_("Viana do Castelo")),
    ("Vila Real", N_("Vila Real")),
    ("Viseu", N_("Viseu")),
    ("Évora", N_("Évora")),
];

pub const SPAIN_RIVERS: &[(&str, &str)] = &[
    ("Bidasoa", N_("Bidasoa")),
    ("Duero", N_("Duero")),
    ("Ebro", N_("Ebro")),
    ("Genil", N_("Genil")),
    ("Guadalete", N_("Guadalete")),
    ("Guadalquivir", N_("Guadalquivir")),
    ("Guadiana", N_("Guadiana")),
    ("Jarama", N_("Jarama")),
    ("Júcar", N_("Júcar")),
    ("Llobregat", N_("Llobregat")),
    ("Miño", N_("Miño")),
    ("Nalón", N_("Nalón")),
    ("Navia", N_("Navia")),
    ("Nervión", N_("Nervión")),
    ("Pisuerga", N_("Pisuerga")),
    ("Segre", N_("Segre")),
    ("Segura", N_("Segura")),
    ("Tajo", N_("Tajo")),
    ("Ter", N_("Ter")),
    ("Turia", N_("Turia")),
];

pub const GALICIA_PROVINCES: &[(&str, &str)] = &[
    ("A Coruña", N_("A Coruña")),
    ("Lugo", N_("Lugo")),
    ("Ourense", N_("Ourense")),
    ("Pontevedra", N_("Pontevedra")),
];

pub const FRANCE_REGIONS: &[(&str, &str)] = &[
    ("Auvergne-Rhône-Alpes", N_("Auvergne-Rhône-Alpes")),
    ("Bourgogne-Franche-Comté", N_("Bourgogne-Franche-Comté")),
    ("Bretagne", N_("Brittany")),
    ("Centre-Val de Loire", N_("Centre-Val de Loire")),
    ("Corse", N_("Corsica")),
    ("Grand Est", N_("Grand Est")),
    ("Guadeloupe", N_("Guadeloupe")),
    ("Guyane", N_("French Guiana")),
    ("Hauts-de-France", N_("Hauts-de-France")),
    ("Île-de-France", N_("Île-de-France")),
    ("La Réunion", N_("Réunion")),
    ("Martinique", N_("Martinique")),
    ("Mayotte", N_("Mayotte")),
    ("Normandie", N_("Normandy")),
    ("Nouvelle-Aquitaine", N_("New Aquitaine")),
    ("Occitanie", N_("Occitanie")),
    ("Pays de la Loire", N_("Pays de la Loire")),
    (
        "Provence-Alpes-Côte d'Azur",
        N_("Provence-Alpes-Côte d'Azur"),
    ),
];

pub const EUROPE_CAPITALS: &[(&str, &str)] = &[
    (N_("Tirana"), N_("Albania")),
    (N_("Andorra la Vella"), N_("Andorra")),
    (N_("Yerevan"), N_("Armenia")),
    (N_("Vienna"), N_("Austria")),
    (N_("Baku"), N_("Azerbaijan")),
    (N_("Minsk"), N_("Belarus")),
    (N_("Brussels"), N_("Belgium")),
    (N_("Sarajevo"), N_("Bosnia and Herzegovina")),
    (N_("Sofia"), N_("Bulgaria")),
    (N_("Zagreb"), N_("Croatia")),
    (N_("Nicosia"), N_("Cyprus")),
    (N_("Prague"), N_("Czech Republic")),
    (N_("Copenhagen"), N_("Denmark")),
    (N_("Tallinn"), N_("Estonia")),
    (N_("Helsinki"), N_("Finland")),
    (N_("Paris"), N_("France")),
    (N_("Tbilisi"), N_("Georgia")),
    (N_("Berlin"), N_("Germany")),
    (N_("Athens"), N_("Greece")),
    (N_("Budapest"), N_("Hungary")),
    (N_("Reykjavik"), N_("Iceland")),
    (N_("Dublin"), N_("Ireland")),
    (N_("Rome"), N_("Italy")),
    (N_("Pristina"), N_("Kosovo")),
    (N_("Riga"), N_("Latvia")),
    (N_("Vaduz"), N_("Liechtenstein")),
    (N_("Vilnius"), N_("Lithuania")),
    (N_("Luxembourg"), N_("Luxembourg")),
    (N_("Valletta"), N_("Malta")),
    (N_("Chisinau"), N_("Moldova")),
    (N_("Monaco"), N_("Monaco")),
    (N_("Podgorica"), N_("Montenegro")),
    (N_("Amsterdam"), N_("Netherlands")),
    (N_("Skopje"), N_("North Macedonia")),
    (N_("Oslo"), N_("Norway")),
    (N_("Warsaw"), N_("Poland")),
    (N_("Lisbon"), N_("Portugal")),
    (N_("Bucharest"), N_("Romania")),
    (N_("Moscow"), N_("Russia")),
    (N_("San Marino"), N_("San Marino")),
    (N_("Belgrade"), N_("Serbia")),
    (N_("Bratislava"), N_("Slovakia")),
    (N_("Ljubljana"), N_("Slovenia")),
    (N_("Madrid"), N_("Spain")),
    (N_("Stockholm"), N_("Sweden")),
    (N_("Bern"), N_("Switzerland")),
    (N_("Ankara"), N_("Turkey")),
    (N_("Kyiv"), N_("Ukraine")),
    (N_("London"), N_("United Kingdom")),
    (N_("Vatican City"), N_("Vatican City")),
];
